[project]
name = "week-10-workshop"
version = "0.1.0"
description = "Model Deployment with Kubernetes and ONNX"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel",
    "requests>=2.32.5",
]

